FROM python:3.6
WORKDIR /Project/patient

ENV REDIS_HOST=
ENV REDIS_PORT=

COPY requirement.txt ./
RUN pip install -r requirement.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

COPY . .

CMD ["gunicorn", "app:app", "-c", "./gunicorn.conf.py"]
