FROM python:3.6
WORKDIR /Project/auth

ENV MYSQL_USER=
ENV MYSQL_PASSWORD=
ENV MYSQL_DB=
ENV MYSQL_HOST=
ENV MYSQL_PORT=

ENV REDIS_HOST=
ENV REDIS_PORT=

COPY requirement.txt ./
RUN pip install -r requirement.txt

COPY . .

CMD ["gunicorn", "app:app", "-c", "./gunicorn.conf.py"]
