FROM python:3.6
WORKDIR /Project/auth

ENV MYSQL_USER=
ENV MYSQL_PASSWORD=
ENV MYSQL_DB=
ENV MYSQL_HOST=
ENV MYSQL_PORT=

ENV REDIS_HOST=
ENV REDIS_PORT=

ENV CONSUL_HOST=
ENV CONSUL_PORT=

ENV SERVICE_NAME=
ENV SERVICE_HOST=
ENV SERVICE_PORT=

COPY requirement.txt ./
RUN pip install -r requirement.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

COPY . .

CMD ["gunicorn", "app:app", "-c", "./gunicorn.conf.py"]
